name: CI

on: [push]
jobs:
  test:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dotfiles
        run: ./install.zsh