name: CI

on: [push]
jobs:
  test:
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dotfiles
        run: |
          export SHELL="/bin/zsh"
          exec $SHELL -l
          ./install.zsh
